#############################################################################
# Makefile for building: fingerterm
# Generated by qmake (2.01a) (Qt 4.8.3) on: Mon Jul 1 11:08:01 2013
# Project:  fingerterm.pro
# Template: app
# Command: /usr/lib/qt4/bin/qmake -o Makefile fingerterm.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_DBUS_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtDBus -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -I. -I/usr/X11R6/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lutil -lQtDeclarative -lQtDBus -lQtOpenGL -lQtGui -lQtCore -lGLESv2 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		terminal.cpp \
		textrender.cpp \
		ptyiface.cpp \
		util.cpp \
		keyloader.cpp \
		mainwindow.cpp \
		dbusadaptor.cpp moc_ptyiface.cpp \
		moc_terminal.cpp \
		moc_textrender.cpp \
		moc_util.cpp \
		moc_keyloader.cpp \
		moc_mainwindow.cpp \
		moc_dbusadaptor.cpp \
		qrc_resources.cpp
OBJECTS       = main.o \
		terminal.o \
		textrender.o \
		ptyiface.o \
		util.o \
		keyloader.o \
		mainwindow.o \
		dbusadaptor.o \
		moc_ptyiface.o \
		moc_terminal.o \
		moc_textrender.o \
		moc_util.o \
		moc_keyloader.o \
		moc_mainwindow.o \
		moc_dbusadaptor.o \
		qrc_resources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		fingerterm.pro
QMAKE_TARGET  = fingerterm
DESTDIR       = 
TARGET        = fingerterm

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: fingerterm.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDeclarative.prl \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile fingerterm.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDeclarative.prl:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile fingerterm.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/fingerterm1.0.0 || $(MKDIR) .tmp/fingerterm1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/fingerterm1.0.0/ && $(COPY_FILE) --parents ptyiface.h terminal.h textrender.h version.h util.h keyloader.h mainwindow.h dbusadaptor.h .tmp/fingerterm1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/fingerterm1.0.0/ && $(COPY_FILE) --parents main.cpp terminal.cpp textrender.cpp ptyiface.cpp util.cpp keyloader.cpp mainwindow.cpp dbusadaptor.cpp .tmp/fingerterm1.0.0/ && (cd `dirname .tmp/fingerterm1.0.0` && $(TAR) fingerterm1.0.0.tar fingerterm1.0.0 && $(COMPRESS) fingerterm1.0.0.tar) && $(MOVE) `dirname .tmp/fingerterm1.0.0`/fingerterm1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/fingerterm1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_ptyiface.cpp moc_terminal.cpp moc_textrender.cpp moc_util.cpp moc_keyloader.cpp moc_mainwindow.cpp moc_dbusadaptor.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ptyiface.cpp moc_terminal.cpp moc_textrender.cpp moc_util.cpp moc_keyloader.cpp moc_mainwindow.cpp moc_dbusadaptor.cpp
moc_ptyiface.cpp: ptyiface.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) ptyiface.h -o moc_ptyiface.cpp

moc_terminal.cpp: terminal.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) terminal.h -o moc_terminal.cpp

moc_textrender.cpp: terminal.h \
		textrender.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) textrender.h -o moc_textrender.cpp

moc_util.cpp: util.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) util.h -o moc_util.cpp

moc_keyloader.cpp: keyloader.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) keyloader.h -o moc_keyloader.cpp

moc_mainwindow.cpp: mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_dbusadaptor.cpp: dbusadaptor.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) dbusadaptor.h -o moc_dbusadaptor.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		data/menu.xml \
		data/english.layout \
		data/finnish.layout \
		qml/LayoutWindow.qml \
		qml/Keyboard.qml \
		qml/Key.qml \
		qml/Main.qml \
		qml/UrlWindow.qml \
		qml/Lineview.qml \
		qml/NotifyWin.qml \
		qml/Button.qml \
		qml/Menu.qml \
		icons/shift.png \
		icons/scroll-indicator.png \
		icons/down.png \
		icons/enter.png \
		icons/up.png \
		icons/menu.png \
		icons/tab.png \
		icons/backspace.png \
		icons/right.png \
		icons/left.png
	/usr/lib/qt4/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp dbusadaptor.h \
		mainwindow.h \
		ptyiface.h \
		terminal.h \
		textrender.h \
		util.h \
		version.h \
		keyloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

terminal.o: terminal.cpp terminal.h \
		ptyiface.h \
		textrender.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o terminal.o terminal.cpp

textrender.o: textrender.cpp textrender.h \
		terminal.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textrender.o textrender.cpp

ptyiface.o: ptyiface.cpp terminal.h \
		ptyiface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ptyiface.o ptyiface.cpp

util.o: util.cpp mainwindow.h \
		terminal.h \
		util.h \
		textrender.h \
		version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o util.o util.cpp

keyloader.o: keyloader.cpp keyloader.h \
		util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyloader.o keyloader.cpp

mainwindow.o: mainwindow.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

dbusadaptor.o: dbusadaptor.cpp dbusadaptor.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbusadaptor.o dbusadaptor.cpp

moc_ptyiface.o: moc_ptyiface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ptyiface.o moc_ptyiface.cpp

moc_terminal.o: moc_terminal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_terminal.o moc_terminal.cpp

moc_textrender.o: moc_textrender.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_textrender.o moc_textrender.cpp

moc_util.o: moc_util.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_util.o moc_util.cpp

moc_keyloader.o: moc_keyloader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyloader.o moc_keyloader.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_dbusadaptor.o: moc_dbusadaptor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dbusadaptor.o moc_dbusadaptor.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

